openapi: 3.0.3
info:
    title: Payment Method Tokens
    description: The Payment Method Tokens API saves payment methods so payers don't have to enter details for future transactions. Payers can check out faster or pay without being present after they agree to save a payment method.<br><br>The API associates a payment method with a temporary setup token. Pass the setup token to the API to exchange the setup token for a permanent token.<br><br>The permanent token represents a payment method that's saved to the vault. This token can be used repeate[...]
    version: "3.1"
    contact: {}
servers:
    - url: https://api-m.sandbox.paypal.com
      description: PayPal Sandbox Environment
    - url: https://api-m.paypal.com
      description: PayPal Live Environment
tags:
    - name: plans
      description: Use the `/billing/plans` resource to create and manage plans.
    - name: subscriptions
      description: Use the `/billing/subscriptions` resource to create and manage subscriptions.
    - name: products
      description: Use `/products` resource to create and manage products.
    - name: orders
      description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/payments</code> endpoint is deprecated. Use the <code>/v2/payments</code> endpoint instead. For details, see <a href="/docs/checkout/integrate/">PayPal Checkout Basic Integration</a>.</blockquote>Use the <code>/orders</code> resource to authorize, capture, void, and show details for an order.<blockquote><strong>Note:</strong> You cannot refund an order directly. Instead, you must refund a completed payment for an o[...]
    - name: orders-payment-actions
      description: Use the `/checkout/orders` resource with the `/pay` action to pay for an order. When you [create an order](#orders_create), the response includes an approval URL. Redirect the customer to this approval URL.
    - name: trackers
      description: Use the `/trackers` resource to create and manage tracking information for PayPal transactions.
    - name: disputes
      description: Use the `/disputes` resource to list disputes, create disputes, show dispute details, and partially a dispute. Normally, an agent at PayPal creates disputes but now you can run test cases in the sandbox that create disputes.
    - name: disputes-actions
      description: Use the `/disputes` resource with a dispute ID and an action to:<ul><li>Accept a claim.</li><li>Accept an offer to resolve a dispute.</li><li>Acknowledge the return of an item related to a dispute.</li><li>Settle a dispute.</li><li>Appeal a dispute.</li><li>Cancel a dispute.</li><li>Change the reason for a dispute.</li><li>Deny an offer to resolve dispute.</li><li>Escalate a dispute to a claim.</li><li>Make an offer to resolve a dispute.</li><li>Make an offer to resolve a disp[...]
    - name: customer-referred-disputes
      description: Use the `/customer/referred-disputes` resource to create a dispute for a referred case that was created by a partner or marketplace, show details for a referred dispute, by ID, notify referred refunds completed to PayPal, notify PayPal about referred dispute adjudication updates, and determine the dispute eligibility for referred disputes.
    - name: validate-eligibility
      description: Use the `/validate-eligibility/` resource to determine whether you can create a case for a transaction.
    - name: compute-metrics
      description: Use the `/compute-metrics` resource to provide metrics for all disputes.
    - name: validate-referred-dispute-eligibility
      description: Use the `/validate-referred-dispute-eligibility` resource to determine whether you can create a referred case for a transaction, by encrypted transaction ID.
    - name: referred-disputes
      description: Use the `/referred-disputes` resource to create a dispute for a referred case that was created by a partner or marketplace, show details for a referred dispute, by ID, notify referred refunds completed to PayPal, notify PayPal about referred dispute adjudication updates, and determine the dispute eligibility for referred disputes.
    - name: referred-disputes-actions
      description: Use the `/referred-disputes` resource with a dispute ID and an action to notify PayPal about adjudication updates for a referred dispute and notify PayPal about a refund for a referred dispute.
    - name: partner-actions
      description: Use the `/disputes/{id}/partner-actions/` resource to show dispute action details and partially update a dispute action.
    - name: search-suggestions
      description: Use the `/search-suggestions` resource to show search suggestions.
    - name: dispute-events
      description: Use the `/dispute-events` resource to send dispute events.
    - name: refund-preference
      description: Use the `/disputes/{id}/provide-refund-preference` resource to provide refund preferences for the dispute.
    - name: merchant-integration
      description: Enables you to get information about a seller-partner integration.
    - name: partner-referrals
      description: Enables you to create and get information about shared customer data.
    - name: partner-referral-link
      description: Links partner-referral data with a PayPal account.
    - name: cancel-onboarding
      description: Enables you to cancel an in-progress seller onboarding.
    - name: partner
      description: Enables you to create, update and read partner agreements and preferences.
    - name: invoices
      description: Use the `/invoices` resource to create, update, and send invoices and invoice reminders. To manage invoices, you can also list invoices, show details for invoices, delete draft invoices, and cancel sent invoices. You can also record payments for invoices to mark them as fully or partially paid, or record refunds for invoices to mark them as fully or partially refunded. You can create QR codes for invoices that can be scanned, viewed, and paid by a mobile phone.
    - name: templates
      description: Use the `/templates` resource to create, list, show details for, update, and delete invoice templates. Use the `/templates` resource when you create a third-party invoicing application. For instance, a business can create a template with predefined invoice data. Later, the business can select the template to populate the invoice data.<blockquote><strong>Note:</strong> To upload a logo to display on an invoice, you can use the <strong>Template Settings</strong> dashboard to <a [...]
    - name: files
      description: Use the `/files` resource to upload a file attachment for an invoice.
    - name: group-invoices
      description: Use the `/group-invoices` resource to create a batch, or group of, invoices.
    - name: search
      description: Use the `/search` resource to search for invoices.
    - name: summaries
      description: Use the `/summaries` resource to list invoice summary information, including counts. The list is grouped by invoice status.
    - name: search-invoices
      description: Use the `/search-invoices` resource to search for and list invoices that match search criteria.
    - name: merchant-config
      description: Use the `/merchant-config` resource to create, update and show details of merchant configuration.
    - name: webhooks
      description: Use the `/webhooks` resource to subscribe your webhook listener to events, list webhooks for an app, show details for, update, delete, and list event subscriptions for webhooks.
    - name: webhooks-lookup
      description: Use the `/webhooks-lookup` resource to create, list, show details for, and delete webhook lookups.
    - name: verify-webhook-signature
      description: Use the `/verify-webhook-signature` resource to verify a webhook signature.
    - name: webhooks-event-types
      description: Use the `/webhooks-event-types` resource to list available events to which any webhook can subscribe.
    - name: webhooks-events
      description: Use the `/webhooks-events` resource to list, show details for, and resend event notifications.
    - name: simulate-event
      description: Use the `/simulate-event` resource to use a sample payload to simulate a webhook event. The events that this call generates only serve to validate the connection to the listener URL and to show how webhook events look. <blockquote><strong>Note:</strong> You can also use the <a href="/docs/api/notifications/webhooks/simulator/">Webhooks simulator</a> to simulate webhook events.</blockquote>
    - name: publish-event-with-payload
      description: Use the `/publish-event-with-payload` resource to publish an event with a specified payload.
    - name: publish-event-with-reference
      description: Use the `/publish-event-with-reference` resource to publish an event with a specified reference.
    - name: webhook-event-delivery-status
      description: Use the `/webhook-event-delivery-status` resource to show the webhook event send status.
    - name: webhooks-error-types
      description: Use the `/error-types` resource to create and list available webhook error types.
    - name: webhooks-errors
      description: Use the `/webhooks-errors` resource to create, list, show details for, and update webhook errors.
    - name: batch-resend
      description: Use the `/batch-resend` resource to send out IPN/Webhooks in batches.
    - name: web-profiles
      description: Use the `/payment-experience/web-profiles` resource to create, show details for, list, update, partially update, and delete web experience profiles.
    - name: payment
      description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/payments</code> endpoint is deprecated. Use the <code>/v2/payments</code> endpoint instead. For details, see <a href="/docs/checkout/integrate/">PayPal Checkout Basic Integration</a>.</blockquote>Use the <code>/payment</code> resource to create a <em>sale</em>, an <em>authorized payment</em>, or an <em>order</em>. A sale is a direct credit card payment, stored credit card payment, or PayPal payment. An authorized p[...]
    - name: sale
      description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/payments</code> endpoint is deprecated. Use the <code>/v2/payments</code> endpoint instead. For details, see <a href="/docs/checkout/integrate/">PayPal Checkout Basic Integration</a>.</blockquote>A <em>sale</em> is a completed payment. Use the <code>/sale</code> resource to show sale details and refund a sale. For more information, see also <a href="/docs/integration/direct/payments/refund-payments/">Refund payment[...]
    - name: authorization
      description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/payments</code> endpoint is deprecated. Use the <code>/v2/payments</code> endpoint instead. For details, see <a href="/docs/checkout/integrate/">PayPal Checkout Basic Integration</a>.</blockquote>Use the <code>/authorization</code> resource and related sub-resources to show details for, capture, void, and reauthorize an authorization.
    - name: capture
      description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/payments</code> endpoint is deprecated. Use the <code>/v2/payments</code> endpoint instead. For details, see <a href="/docs/checkout/integrate/">PayPal Checkout Basic Integration</a>.</blockquote>Use the <code>/capture</code> resource and sub-resources to show details for and refund captured payments.
    - name: refund
      description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/payments</code> endpoint is deprecated. Use the <code>/v2/payments</code> endpoint instead. For details, see <a href="/docs/checkout/integrate/">PayPal Checkout Basic Integration</a>.</blockquote>Use the <code>/refund</code> resource to show details for a refund on direct and captured payments.
    - name: receipt
      description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/payments</code> endpoint is deprecated. Use the <code>/v2/payments</code> endpoint instead. For details, see <a href="/docs/checkout/integrate/">PayPal Checkout Basic Integration</a>.</blockquote>Use the <code>/receipt</code> resource to show details for a payment receipt.
    - name: authorizations
      description: Use the `/authorizations` resource to show details for, capture payment for, reauthorize, and void authorized payments.
    - name: captures
      description: Use the `/captures` resource to show details for and refund a captured payment.
    - name: refunds
      description: Use the `/refunds` resource to show refund details.
    - name: assets
      description: Assets APIs for Checkout
    - name: cancel-payment
      description: Use the <code>/cancel-payment</code> resource to cancel an order capture or order authorization by <code>PayPal-Request-Id</code>. The merchant triggers the cancel action.
    - name: find-eligible-methods
      description: Use the `/find-eligible-methods` resource to show list of eligible payment methods for given customer/order context.
    - name: payment-resource-operations
      description: Use the `/payment-resource-operations` resource to show verifications details.
    - name: payouts
      description: Use the `/payouts` resource to create a batch payout, update the status for a batch payout, show the status of a batch payout with the transaction status and other data for individual payout items, and request approval for a batch payout.
    - name: payouts-item
      description: Use the `/payouts-item` resource to show payout item details and cancel an unclaimed payout item.
    - name: payouts-statistics
      description: Use the `/payouts-statistics` resource to show statistics for a batch payout by date range.
    - name: payouts-disbursement-notifications
      description: Use the `payouts/disbursement-notifications` resource for status updates from <code>VENMO</code>
    - name: transactions
      description: Use the `/transactions` resource to list transactions.
    - name: partner-transactions
      description: Use the `/partner-transactions` resource to list transactions.
    - name: balances
      description: Use the `/balances` resource to list balances.
    - name: trackers-batch
      description: Use the `/trackers-batch` resource to add tracking information for multiple PayPal transactions.
    - name: carriers-recommend
      description: Use the `/carriers-recommendations` to detect the possible carriers corresponding the tracking info from tracking aggregator.
    - name: carriers
      description: Use the `/carriers` resource to list/detect all the carriers available for tracking in PayPal and its subsidiary.
    - name: shipments
      description: Use the `/shipments` resource to fetch all the shipments associated with a given Paypal Account Id.
    - name: shipment-tracker
      description: Use the `/shipment-tracker` resource to track the shipment.
    - name: unsubscribe-shipment-tracking
      description: Use the `/unsubscribe-shipment-tracking` resource to unsubscribe from multiple shipments.
    - name: payment-tokens
      description: Use the `/vault/payment-tokens` resource to create, retrieve, and delete a payment token that may optionally be associated with a customer.
    - name: setup-tokens
      description: Use the `/vault/setup-tokens` resource to create and retrieve temporary vault payment methods.
    - name: tokens
      description: Use the `/vault/tokens` resource to detokenize a vault token to retrieve details associated to the underlying payment source.
    - name: customers
      description: Use the `/vault/customers` resource to create, update, get and delete a customer.
paths:
    /v1/billing/plans:
        post:
            summary: Create plan
            description: Creates a plan that defines pricing and billing cycle details for subscriptions.
            operationId: plans.create
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/subscriptions
            tags:
                - plans
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        get:
            summary: List plans
            description: Lists billing plans.
            operationId: plans.list
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/subscriptions
            tags:
                - plans
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/billing/plans/{id}:
        get:
            summary: Show plan details
            description: Shows details for a plan, by ID.
            operationId: plans.get
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/subscriptions
            tags:
                - plans
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        patch:
            summary: Update plan
            description: Updates a plan with the `CREATED` or `ACTIVE` status. For an `INACTIVE` plan, you can make only status updates.<br/>You can patch these attributes and objects:<table><thead><tr><th>Attribute or object</th><th>Operations</th></tr></thead><tbody><tr><td><code>description</code></td><td>replace</td></tr><tr><td><code>payment_preferences.auto_bill_outstanding</code></td><td>replace</td></tr><tr><td><code>taxes.percentage</code></td><td>replace</td></tr><tr><td><code>payment_[...]
            operationId: plans.patch
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/subscriptions
            tags:
                - plans
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/billing/plans/{id}/activate:
        post:
            summary: Activate plan
            description: Activates a plan, by ID.
            operationId: plans.activate
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/subscriptions
            tags:
                - plans
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/billing/plans/{id}/deactivate:
        post:
            summary: Deactivate plan
            description: Deactivates a plan, by ID.
            operationId: plans.deactivate
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/subscriptions
            tags:
                - plans
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/billing/plans/{id}/update-pricing-schemes:
        post:
            summary: Update pricing
            description: Updates pricing for a plan. For example, you can update a regular billing cycle from $5 per month to $7 per month.
            operationId: plans.update-pricing-schemes
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/subscriptions
            tags:
                - plans
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/billing/subscriptions:
        post:
            summary: Create subscription
            description: Creates a subscription.
            operationId: subscriptions.create
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/subscriptions
            tags:
                - subscriptions
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/billing/subscriptions/{id}:
        get:
            summary: Show subscription details
            description: Shows details for a subscription, by ID.
            operationId: subscriptions.get
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/subscriptions
            tags:
                - subscriptions
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        patch:
            summary: Update subscription
            description: Updates a subscription which could be in <code>ACTIVE</code> or <code>SUSPENDED</code> status. You can override plan level default attributes by providing customised values for plan path in the patch request.<br /> <ul> <li>You cannot update attributes that have already completed (Example - trial cycles canΓÇÖt be updated if completed).</li> <li>Once overridden, changes to plan resource will not impact subscription.</li> <li>Any price update will not impact billing cycle[...]
            operationId: subscriptions.patch
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/subscriptions
            tags:
                - subscriptions
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/billing/subscriptions/{id}/revise:
        post:
            summary: Revise plan or quantity of subscription
            description: Updates the quantity of the product or service in a subscription. You can also use this method to switch the plan and update the `shipping_amount`, `shipping_address` values for the subscription. This type of update requires the buyer's consent.
            operationId: subscriptions.revise
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/subscriptions
            tags:
                - subscriptions
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/billing/subscriptions/{id}/suspend:
        post:
            summary: Suspend subscription
            description: Suspends the subscription.
            operationId: subscriptions.suspend
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/subscriptions
            tags:
                - subscriptions
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/billing/subscriptions/{id}/cancel:
        post:
            summary: Cancel subscription
            description: Cancels the subscription.
            operationId: subscriptions.cancel
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/subscriptions
            tags:
                - subscriptions
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/billing/subscriptions/{id}/activate:
        post:
            summary: Activate subscription
            description: Activates the subscription.
            operationId: subscriptions.activate
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/subscriptions
            tags:
                - subscriptions
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/billing/subscriptions/{id}/capture:
        post:
            summary: Capture authorized payment on subscription
            description: Captures an authorized payment from the subscriber on the subscription.
            operationId: subscriptions.capture
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/subscriptions
            tags:
                - subscriptions
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/billing/subscriptions/{id}/transactions:
        get:
            summary: List transactions for subscription
            description: Lists transactions for a subscription.
            operationId: subscriptions.transactions
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/subscriptions
            tags:
                - subscriptions
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/catalogs/products:
        post:
            summary: Create product
            description: Creates a product.
            operationId: products.create
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/subscriptions
            tags:
                - products
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        get:
            summary: List products
            description: Lists products.
            operationId: products.list
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/subscriptions
            tags:
                - products
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/catalogs/products/{product_id}:
        get:
            summary: Show product details
            description: Shows details for a product, by ID.
            operationId: products.get
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/subscriptions
            tags:
                - products
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        patch:
            summary: Update product
            description: Updates a product, by ID. You can patch these attributes and objects:<table><thead><tr><th>Attribute or object</th><th>Operations</th></tr></thead><tbody><tr><td><code>description</code></td><td>add, replace, remove</td></tr><tr><td><code>category</code></td><td>add, replace, remove</td></tr><tr><td><code>image_url</code></td><td>add, replace, remove</td></tr><tr><td><code>home_url</code></td><td>add, replace, remove</td></tr></tbody></table>
            operationId: products.patch
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/subscriptions
            tags:
                - products
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/checkout/orders:
        post:
            summary: Create order
            description: Creates an order.
            operationId: orders.create
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                    - https://uri.paypal.com/services/payments/channelpartner
                    - https://uri.paypal.com/services/payments/partnerfee
                    - https://uri.paypal.com/services/payments/realtimepayment
            tags:
                - orders
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/checkout/orders/{order_id}:
        get:
            summary: Show order details
            description: Shows details for an order, by ID.
            operationId: orders.get
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                    - https://uri.paypal.com/services/payments/channelpartner
                    - https://uri.paypal.com/services/payments/partnerfee
                    - https://uri.paypal.com/services/payments/realtimepayment
            tags:
                - orders
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        delete:
            summary: Cancel order
            description: Cancels an order, by ID, and deletes the order. To call this method, the order status must be  `CREATED` or `APPROVED`.
            operationId: orders.cancel
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                    - https://uri.paypal.com/services/payments/realtimepayment
            tags:
                - orders
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/checkout/orders/{order_id}/pay:
        post:
            summary: Pay for order
            description: Initiates a PayPal payment that a buyer has approved.<blockquote><strong>Note:</strong> For Partner use cases, use the <code>disbursement_mode</code> to indicate whether to disburse funds to the seller and partner accounts immediately or later. If you delay disbursement, you must call <a href="/docs/multiparty/checkout/delayed-disbursement/">disburse funds</a> to disburse funds to the merchant and partner.</blockquote>
            operationId: orders.pay
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                    - https://uri.paypal.com/services/payments/realtimepayment
            tags:
                - orders-payment-actions
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v2/checkout/orders:
        post:
            summary: Create order
            description: Creates an order. Merchants and partners can add Level 2 and 3 data to payments to reduce risk and payment processing costs. For more information about processing payments, see <a href="https://developer.paypal.com/docs/checkout/advanced/processing/">checkout</a> or <a href="https://developer.paypal.com/docs/multiparty/checkout/advanced/processing/">multiparty checkout</a>.<blockquote><strong>Note:</strong> For error handling and troubleshooting, see <a href="/api/rest/r[...]
            operationId: orders.create
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                    - https://uri.paypal.com/services/payments/orders/client-side-integration
            tags:
                - orders
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v2/checkout/orders/{id}:
        get:
            summary: Show order details
            description: Shows details for an order, by ID.<blockquote><strong>Note:</strong> For error handling and troubleshooting, see <a href="/api/rest/reference/orders/v2/errors/#get-order">Orders v2 errors</a>.</blockquote>
            operationId: orders.get
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                    - https://uri.paypal.com/services/payments/orders/client-side-integration
            tags:
                - orders
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        patch:
            summary: Update order
            description: 'Updates an order with a `CREATED` or `APPROVED` status. You cannot update an order with the `COMPLETED` status.<br/><br/>To make an update, you must provide a `reference_id`. If you omit this value with an order that contains only one purchase unit, PayPal sets the value to `default` which enables you to use the path: <code>\"/purchase_units/@reference_id==''default''/{attribute-or-object}\"</code>. Merchants and partners can add Level 2 and 3 data to payments to reduce[...]'
            operationId: orders.patch
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                    - https://uri.paypal.com/services/payments/orders/client-side-integration
            tags:
                - orders
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v2/checkout/orders/{id}/confirm-payment-source:
        post:
            summary: Confirm the Order
            description: Payer confirms their intent to pay for the the Order with the given payment source.
            operationId: orders.confirm
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                    - https://uri.paypal.com/services/payments/initiatepayment
            tags:
                - orders
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v2/checkout/orders/{id}/authorize:
        post:
            summary: Authorize payment for order
            description: Authorizes payment for an order. To successfully authorize payment for an order, the buyer must first approve the order or a valid payment_source must be provided in the request. A buyer can approve the order upon being redirected to the rel:approve URL that was returned in the HATEOAS links in the create order response.<blockquote><strong>Note:</strong> For error handling and troubleshooting, see <a href="/api/rest/reference/orders/v2/errors/#authorize-order">Orders v2 [...]
            operationId: orders.authorize
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                    - https://uri.paypal.com/services/payments/orders/client-side-integration
            tags:
                - orders
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v2/checkout/orders/{id}/capture:
        post:
            summary: Capture payment for order
            description: Captures payment for an order. To successfully capture payment for an order, the buyer must first approve the order or a valid payment_source must be provided in the request. A buyer can approve the order upon being redirected to the rel:approve URL that was returned in the HATEOAS links in the create order response.<blockquote><strong>Note:</strong> For error handling and troubleshooting, see <a href="/api/rest/reference/orders/v2/errors/#capture-order">Orders v2 errors[...]
            operationId: orders.capture
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                    - https://uri.paypal.com/services/payments/orders/client-side-integration
            tags:
                - orders
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v2/checkout/orders/{id}/track:
        post:
            summary: Add tracking information for an Order.
            description: Adds tracking information for an Order.
            operationId: orders.track.create
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
            tags:
                - orders
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v2/checkout/orders/{id}/trackers/{tracker_id}:
        patch:
            summary: Update or cancel tracking information for a PayPal order
            description: Updates or cancels the tracking information for a PayPal order, by ID. Updatable attributes or objects:<br/><br/><table><thead><th>Attribute</th><th>Op</th><th>Notes</th></thead><tbody></tr><tr><td><code>items</code></td><td>replace</td><td>Using replace op for <code>items</code> will replace the entire <code>items</code> object with the value sent in request.</td></tr><tr><td><code>notify_payer</code></td><td>replace, add</td><td></td></tr><tr><td><code>status</code></t[...]
            operationId: orders.trackers.patch
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
            tags:
                - trackers
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/customer/disputes:
        get:
            summary: List disputes
            description: Lists disputes with a summary set of details, which shows the <code>dispute_id</code>, <code>reason</code>, <code>status</code>, <code>dispute_state</code>, <code>dispute_life_cycle_stage</code>, <code>dispute_channel</code>, <code>dispute_amount</code>, <code>create_time</code> and <code>update_time</code> fields.<br/><br/>To filter the disputes in the response, specify one or more optional query parameters. To limit the number of disputes in the response, specify the <[...]
            operationId: disputes.list
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/disputes/read-buyer
                - Oauth2:
                    - https://uri.paypal.com/services/disputes/read-seller
                - Oauth2:
                    - https://uri.paypal.com/services/disputes/read-ebay
                - Oauth2:
                    - https://uri.paypal.com/services/disputes/read
                - Oauth2:
                    - https://uri.paypal.com/services/disputes/read-partner
            tags:
                - disputes
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/customer/disputes/{id}:
        get:
            summary: Show dispute details
            description: Shows details for a dispute, by ID.<blockquote><strong>Note:</strong> The fields that appear in the response depend on the access. For example, if the merchant requests shows dispute details, the customer's email ID does not appear.</blockquote>
            operationId: disputes.get
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/disputes/read-buyer
                - Oauth2:
                    - https://uri.paypal.com/services/disputes/read-seller
                - Oauth2:
                    - https://uri.paypal.com/services/disputes/read-ebay
                - Oauth2:
                    - https://uri.paypal.com/services/disputes/read
                - Oauth2:
                    - https://uri.paypal.com/services/disputes/read-partner
            tags:
                - disputes
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        patch:
            summary: Partially update dispute
            description: Partially updates a dispute, by ID. Seller can update the `communication_detail` value or The partner can add the `partner action` information.
            operationId: disputes.patch
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/disputes/update-seller
            tags:
                - disputes
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/customer/disputes/{id}/provide-evidence:
        post:
            summary: Provide evidence
            description: Provides evidence for a dispute, by ID. A merchant can provide evidence for disputes with the <code>WAITING_FOR_SELLER_RESPONSE</code> status while customers can provide evidence for disputes with the <code>WAITING_FOR_BUYER_RESPONSE</code> status. Evidence can be a proof of delivery or proof of refund document or notes, which can include logs. A proof of delivery document includes a tracking number while a proof of refund document includes a refund ID. For other evidenc[...]
            operationId: disputes.provide-evidence
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/disputes/update-seller
                - Oauth2:
                    - https://uri.paypal.com/services/disputes/update-buyer
                - Oauth2:
                    - https://uri.paypal.com/services/disputes/update-partner
            tags:
                - disputes-actions
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/customer/disputes/{id}/appeal:
        post:
            summary: Appeal dispute
            description: Appeals a dispute, by ID. To appeal a dispute, use the <code>appeal</code> link in the <a href="/docs/api/reference/api-responses/#hateoas-links/">HATEOAS links</a> from the show dispute details response. If this link does not appear, you cannot appeal the dispute. Submit new evidence as a document or notes in the JSON request body. For constraints and rules regarding documents, see <a href="/docs/integration/direct/customer-disputes/integration-guide/#documents">documen[...]
            operationId: disputes.appeal
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/disputes/update-seller
                - Oauth2:
                    - https://uri.paypal.com/services/disputes/update-buyer
            tags:
                - disputes-actions
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/customer/disputes/{id}/accept-claim:
        post:
            summary: Accept claim
            description: Accepts liability for a claim, by ID. When you accept liability for a claim, the dispute closes in the customerΓÇÖs favor and PayPal automatically refunds money to the customer from the merchant's account. Allowed accept_claim_type values for the request is available in dispute details <a href="/docs/api/customer-disputes/v1/#definition-allowed_response_options">allowed response options</a> object.
            operationId: disputes.accept-claim
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/disputes/update-seller
            tags:
                - disputes-actions
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/customer/disputes/{id}/adjudicate:
        post:
            summary: Settle dispute
            description: <blockquote><strong>Important:</strong> This method is for sandbox use only.</blockquote> Settles a dispute in either the customer's or merchant's favor. Merchants can make this call in the sandbox to complete end-to-end dispute resolution testing, which mimics the dispute resolution that PayPal agents normally complete. To make this call, the dispute <code>status</code> must be <code>UNDER_REVIEW</code> and <code>adjudicate</code> link  should be available in the <a hre[...]
            operationId: disputes.adjudicate
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/disputes/update-seller
                - Oauth2:
                    - https://uri.paypal.com/services/disputes/update-buyer
            tags:
                - disputes-actions
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/customer/disputes/{id}/require-evidence:
        post:
            summary: Update dispute status
            description: <blockquote><strong>Important:</strong> This method is for sandbox use only.</blockquote> Updates the status of a dispute, by ID, from <code>UNDER_REVIEW</code> to either:<ul><li><code>WAITING_FOR_BUYER_RESPONSE</code></li><li><code>WAITING_FOR_SELLER_RESPONSE</code></li></ul>This status change enables either the customer or merchant to submit evidence for the dispute. To make this call, the dispute <code>status</code> must be <code>UNDER_REVIEW</code> and <code>require-[...]
            operationId: disputes.require-evidence
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/disputes/update-seller
                - Oauth2:
                    - https://uri.paypal.com/services/disputes/update-buyer
            tags:
                - disputes-actions
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/customer/disputes/{id}/escalate:
        post:
            summary: Escalate dispute to claim
            description: Escalates the dispute, by ID, to a PayPal claim. To make this call, the stage in the dispute lifecycle must be `INQUIRY`.
            operationId: disputes.escalate
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/disputes/update-seller
                - Oauth2:
                    - https://uri.paypal.com/services/disputes/update-buyer
            tags:
                - disputes-actions
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/customer/disputes/{id}/send-message:
        post:
            summary: Send message about dispute to other party
            description: Sends a message about a dispute, by ID, to the other party in the dispute. Merchants and customers can only send messages if the `dispute_life_cycle_stage` value is `INQUIRY`. For constraints and rules regarding documents that can be attached as part of the message, see <a href="/docs/integration/direct/customer-disputes/integration-guide/#documents">documents</a>. To send a message, use the <code>send-message</code> link in the <a href="/docs/api/reference/api-responses[...]
            operationId: disputes.send-message
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/disputes/update-seller
                - Oauth2:
                    - https://uri.paypal.com/services/disputes/update-buyer
            tags:
                - disputes-actions
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/customer/disputes/{id}/make-offer:
        post:
            summary: Make offer to resolve dispute
            description: Makes an offer to the other party to resolve a dispute, by ID. To make this call, the stage in the dispute lifecycle must be `INQUIRY`. If the customer accepts the offer, PayPal automatically makes a refund. Allowed offer_type values for the request is available in dispute details <a href="/docs/api/customer-disputes/v1/#definition-allowed_response_options">allowed response options</a> object.
            operationId: disputes.make-offer
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/disputes/update-seller
                - Oauth2:
                    - https://uri.paypal.com/services/disputes/update-buyer
            tags:
                - disputes-actions
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/customer/disputes/{id}/accept-offer:
        post:
            summary: Accept offer to resolve dispute
            description: The customer accepts the offer from merchant to resolve a dispute, by ID. PayPal automatically refunds the amount proposed by merchant to the customer.
            operationId: disputes.accept-offer
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/disputes/update-buyer
            tags:
                - disputes-actions
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/customer/disputes/{id}/deny-offer:
        post:
            summary: Deny offer to resolve dispute
            description: Denies an offer that the merchant proposes for a dispute, by ID.
            operationId: disputes.deny-offer
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/disputes/update-buyer
            tags:
                - disputes-actions
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/customer/disputes/{id}/acknowledge-return-item:
        post:
            summary: Acknowledge returned item
            description: Acknowledges that the customer returned an item for a dispute, by ID. A merchant can make this request for disputes with the `MERCHANDISE_OR_SERVICE_NOT_AS_DESCRIBED` reason. Allowed acknowledgement_type values for the request is available in dispute details <a href="/docs/api/customer-disputes/v1/#definition-allowed_response_options">allowed response options</a> object. For constraints and rules regarding documents, see <a href="/docs/integration/direct/customer-dispute[...]
            operationId: disputes.acknowledge-return-item
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/disputes/update-seller
            tags:
                - disputes-actions
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/customer/disputes/{id}/provide-supporting-info:
        post:
            summary: Provide supporting information for dispute
            description: Provides supporting information for a dispute, by ID. A merchant or buyer can make this request for disputes if they find the `provide-supporting-info` link in the HATEOAS links in the list disputes response. The party can provide the supporting information to PayPal to defend themselves only when the `dispute_life_cycle_stage` is `CHARGEBACK`, `PRE_ARBITRATION`, or `ARBITRATION`. They can provide a note that describes their part with details or upload any supporting doc[...]
            operationId: disputes.provide-supporting-info
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/disputes/update-seller
                    - https://uri.paypal.com/services/disputes/update-buyer
                    - https://uri.paypal.com/services/disputes/update-partner
            tags:
                - disputes-actions
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/customer/partner-referrals:
        post:
            summary: Create partner referral
            description: Creates a partner referral that is shared by the API caller. The referrals contains the client's personal, business, and financial data.
            operationId: partner-referrals.create
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/customer/partner-referrals/readwrite
            tags:
                - partner-referrals
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/customer/partner-referrals/{partner_referral_id}:
        get:
            summary: Show referral data
            description: Shows details for referral data, by ID, that was shared by the API caller.
            operationId: partner-referrals.read
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/customer/partner-referrals/readwrite
                - Oauth2:
                    - https://uri.paypal.com/services/customer/partner-referrals
            tags:
                - partner-referrals
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/customer/partners/{partner_id}/merchant-integrations:
        get:
            summary: List seller tracking information
            description: Lists sellers that a partner onboarded, by partner ID.
            operationId: merchant-integration.find
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/customer/partner
            tags:
                - merchant-integration
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/customer/partners/{partner_id}/merchant-integrations/{merchant_id}:
        get:
            summary: Show seller status
            description: Shows status information for sellers that the partner on-boards, by partner ID.
            operationId: merchant-integration.status
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/customer/partner
            tags:
                - merchant-integration
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/customer/partners/{partner_id}/merchant-integrations/credentials:
        get:
            summary: Fetch merchant credentials
            description: Fetches merchant credentials for a merchant onboarded through downloadable cart flow.
            operationId: merchant-integration.credentials
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/customer/partner
            tags:
                - merchant-integration
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/customer/partners/{id}:
        get:
            summary: Show partner information - agreements and preferences
            description: Shows partner information - agreements and preferences - by partner ID.
            operationId: partner.read
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/customer/partner
            tags:
                - partner
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        post:
            summary: Create partner information - agreements and preferences
            description: Creates partner information - agreements and preferences - for the given partner.
            operationId: partner.create
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/customer/partner
            tags:
                - partner
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        put:
            summary: Update partner information - agreements and preferences
            description: Updates partner information - agreements and preferences - for the given partner.
            operationId: partner.update
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/customer/partner
            tags:
                - partner
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v2/customer/partner-referrals:
        post:
            summary: Create partner referral
            description: Creates a partner referral that is shared by the partner or API caller. The partner referral is used to onboard the seller, and contains the seller's personal, business, financial and operations.
            operationId: partner-referrals.create
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/customer/partner-referrals/readwrite
            tags:
                - partner-referrals
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v2/customer/partner-referrals/{partner_referral_id}:
        get:
            summary: Show referral data
            description: Shows details by ID for referral data that was shared by the partner or API caller.
            operationId: partner-referrals.read
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/customer/partner-referrals/readwrite
                - Oauth2:
                    - https://uri.paypal.com/services/customer/partner-referrals
            tags:
                - partner-referrals
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/invoicing/invoices:
        post:
            summary: Create draft invoice
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/invoices</code> endpoint is deprecated. Use the <code>/v2/invoices</code> endpoint instead. For details, see <a href="/docs/invoicing/basic-integration/">PayPal Invoicing Basic Integration</a>.</blockquote>Creates a draft invoice. To move the invoice from a draft to payable state, you must <a href="/docs/api/invoicing/v1/#invoices_send">send the invoice</a>.<br/><br/>In the JSON request body, include invoice [...]
            operationId: invoice.create
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing
            tags:
                - invoices
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        get:
            summary: List invoices
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/invoices</code> endpoint is deprecated. Use the <code>/v2/invoices</code> endpoint instead. For details, see <a href="/docs/invoicing/basic-integration/">PayPal Invoicing Basic Integration</a>.</blockquote>Lists invoices. To filter the invoices that appear in the response, you can specify one or more optional query parameters.
            operationId: invoice.get_all
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing
            tags:
                - invoices
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/invoicing/search:
        post:
            summary: Search for invoices
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/invoices</code> endpoint is deprecated. Use the <code>/v2/invoices</code> endpoint instead. For details, see <a href="/docs/invoicing/basic-integration/">PayPal Invoicing Basic Integration</a>.</blockquote>Searches for invoices that match search criteria. If you pass multiple criteria, the response lists invoices that match all criteria.
            operationId: invoice.search
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing
            tags:
                - search
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/invoicing/invoices/{invoice_id}/send:
        post:
            summary: Send invoice
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/invoices</code> endpoint is deprecated. Use the <code>/v2/invoices</code> endpoint instead. For details, see <a href="/docs/invoicing/basic-integration/">PayPal Invoicing Basic Integration</a>.</blockquote>Sends an invoice, by ID, to a customer. To suppress the merchant's email notification, set the `notify_merchant` query parameter to `false`.<blockquote><strong>Note:</strong> After you send an invoice, you [...]
            operationId: invoice.send
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing
            tags:
                - invoices
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/invoicing/invoices/{invoice_id}/schedule:
        post:
            summary: Schedule invoice
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/invoices</code> endpoint is deprecated. Use the <code>/v2/invoices</code> endpoint instead. For details, see <a href="/docs/invoicing/basic-integration/">PayPal Invoicing Basic Integration</a>.</blockquote>Schedules an invoice, by ID, to send on a future date. At 07:00 on that date in the preferred time zone of the merchant's PayPal account profile, PayPal emails an invoice notification to the merchant and th[...]
            operationId: invoice.schedule
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing
            tags:
                - invoices
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/invoicing/invoices/{invoice_id}/remind:
        post:
            summary: Send invoice reminder
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/invoices</code> endpoint is deprecated. Use the <code>/v2/invoices</code> endpoint instead. For details, see <a href="/docs/invoicing/basic-integration/">PayPal Invoicing Basic Integration</a>.</blockquote>Sends a reminder to the payer about an invoice, by ID. In the JSON request body, include a `notification` object that defines the subject of the reminder and other details.
            operationId: invoice.remind
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing
            tags:
                - invoices
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/invoicing/invoices/{invoice_id}/cancel:
        post:
            summary: Cancel sent invoice
            description: '<blockquote><strong>Deprecation notice:</strong> The <code>/v1/invoices</code> endpoint is deprecated. Use the <code>/v2/invoices</code> endpoint instead. For details, see <a href="/docs/invoicing/basic-integration/">PayPal Invoicing Basic Integration</a>.</blockquote>Cancels a sent invoice, by ID, and, optionally, sends a notification about the cancellation to the payer, merchant, and CC: emails.'
            operationId: invoice.cancel
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing
            tags:
                - invoices
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/invoicing/invoices/{invoice_id}/record-payment:
        post:
            summary: Mark invoice as paid
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/invoices</code> endpoint is deprecated. Use the <code>/v2/invoices</code> endpoint instead. For details, see <a href="/docs/invoicing/basic-integration/">PayPal Invoicing Basic Integration</a>.</blockquote>Marks the status of an invoice, by ID, as paid.
            operationId: invoice.record-payment
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing
            tags:
                - invoices
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/invoicing/invoices/{invoice_id}/record-refund:
        post:
            summary: Mark invoice as refunded
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/invoices</code> endpoint is deprecated. Use the <code>/v2/invoices</code> endpoint instead. For details, see <a href="/docs/invoicing/basic-integration/">PayPal Invoicing Basic Integration</a>.</blockquote>Marks the status of an invoice, by ID, as refunded.
            operationId: invoice.record-refund
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing
            tags:
                - invoices
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/invoicing/invoices/{invoice_id}:
        get:
            summary: Show invoice details
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/invoices</code> endpoint is deprecated. Use the <code>/v2/invoices</code> endpoint instead. For details, see <a href="/docs/invoicing/basic-integration/">PayPal Invoicing Basic Integration</a>.</blockquote>Shows details for an invoice, by ID.
            operationId: invoice.get
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing
            tags:
                - invoices
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        put:
            summary: Update invoice
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/invoices</code> endpoint is deprecated. Use the <code>/v2/invoices</code> endpoint instead. For details, see <a href="/docs/invoicing/basic-integration/">PayPal Invoicing Basic Integration</a>.</blockquote>Fully updates an invoice, by ID. In the JSON request body, include a complete `invoice` object. This call does not support partial updates.
            operationId: invoice.update
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing
            tags:
                - invoices
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        delete:
            summary: Delete draft invoice
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/invoices</code> endpoint is deprecated. Use the <code>/v2/invoices</code> endpoint instead. For details, see <a href="/docs/invoicing/basic-integration/">PayPal Invoicing Basic Integration</a>.</blockquote>Deletes invoices in the <code>DRAFT</code> or <code>SCHEDULED</code> state, by ID. For invoices that have already been sent, you can <a href="/docs/api/invoicing/v1/#invoices_cancel">cancel the invoice</a>.[...]
            operationId: invoice.delete
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing
            tags:
                - invoices
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/invoicing/invoices/{invoice_id}/payment-records/{transaction_id}:
        delete:
            summary: Delete external payment
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/invoices</code> endpoint is deprecated. Use the <code>/v2/invoices</code> endpoint instead. For details, see <a href="/docs/invoicing/basic-integration/">PayPal Invoicing Basic Integration</a>.</blockquote>Deletes an external payment, by invoice ID and transaction ID.
            operationId: invoice.delete_external_payment
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing
            tags:
                - invoices
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/invoicing/invoices/{invoice_id}/refund-records/{transaction_id}:
        delete:
            summary: Delete external refund
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/invoices</code> endpoint is deprecated. Use the <code>/v2/invoices</code> endpoint instead. For details, see <a href="/docs/invoicing/basic-integration/">PayPal Invoicing Basic Integration</a>.</blockquote>Deletes an external refund, by invoice ID and transaction ID.
            operationId: invoice.delete_external_refund
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing
            tags:
                - invoices
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/invoicing/invoices/{invoice_id}/qr-code:
        get:
            summary: Generate QR code
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/invoices</code> endpoint is deprecated. Use the <code>/v2/invoices</code> endpoint instead. For details, see <a href="/docs/invoicing/basic-integration/">PayPal Invoicing Basic Integration</a>.</blockquote>Generates a QR code for an invoice, by ID. The QR code is a PNG image in <a href="https://www.base64encode.org/">Base64-encoded</a> format that corresponds to the invoice ID. You can generate a QR code for [...]
            operationId: invoice.qr_code
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing
            tags:
                - invoices
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/invoicing/invoices/next-invoice-number:
        post:
            summary: Generate invoice number
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/invoices</code> endpoint is deprecated. Use the <code>/v2/invoices</code> endpoint instead. For details, see <a href="/docs/invoicing/basic-integration/">PayPal Invoicing Basic Integration</a>.</blockquote>Generates the next invoice number that is available to the merchant. The next invoice number uses the prefix and suffix from the last invoice number and increments the number by one. For example, the next i[...]
            operationId: invoice.next_invoice_number
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing
            tags:
                - invoices
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/invoicing/templates:
        post:
            summary: Create template
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/invoices</code> endpoint is deprecated. Use the <code>/v2/invoices</code> endpoint instead. For details, see <a href="/docs/invoicing/basic-integration/">PayPal Invoicing Basic Integration</a>.</blockquote>Creates an invoice template. You can use details from this template to create an invoice. You can create up to 50 templates.<blockquote><strong>Note:</strong> Every merchant starts with three PayPal system [...]
            operationId: template.create
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing
            tags:
                - templates
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        get:
            summary: List templates
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/invoices</code> endpoint is deprecated. Use the <code>/v2/invoices</code> endpoint instead. For details, see <a href="/docs/invoicing/basic-integration/">PayPal Invoicing Basic Integration</a>.</blockquote>Lists merchant-created templates with associated details. The associated details include the email addresses, postal addresses, and phone numbers from the user's PayPal profile.<br/>The user can select whic[...]
            operationId: template.get_templates
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing
            tags:
                - templates
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/invoicing/templates/{template_id}:
        get:
            summary: Show template details
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/invoices</code> endpoint is deprecated. Use the <code>/v2/invoices</code> endpoint instead. For details, see <a href="/docs/invoicing/basic-integration/">PayPal Invoicing Basic Integration</a>.</blockquote>Shows details for a template, by ID.
            operationId: template.get
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing
            tags:
                - templates
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        delete:
            summary: Delete template
            description: Deletes a template, by ID.
            operationId: template.delete
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing
            tags:
                - templates
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        put:
            summary: Update template
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/invoices</code> endpoint is deprecated. Use the <code>/v2/invoices</code> endpoint instead. For details, see <a href="/docs/invoicing/basic-integration/">PayPal Invoicing Basic Integration</a>.</blockquote>Updates a template, by ID. In the JSON request body, specify a complete `template` object. The update method does not support partial updates.
            operationId: template.update
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing
            tags:
                - templates
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v2/invoicing/invoices:
        post:
            summary: Create draft invoice
            description: Creates a draft invoice. To move the invoice from a draft to payable state, you must <a href="#invoices_send">send the invoice</a>.<br/><br/>In the JSON request body, include invoice details including merchant information. The <code>invoice</code> object must include an <code>items</code> array.<blockquote><strong>Note:</strong> The merchant that you specify in an invoice must have a PayPal account in good standing.</blockquote>.
            operationId: invoices.create
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing/invoices/readwrite
            tags:
                - invoices
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        get:
            summary: List invoices
            description: Lists invoices. To filter the invoices that appear in the response, you can specify one or more optional query parameters.
            operationId: invoices.list
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing/invoices/read
            tags:
                - invoices
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v2/invoicing/invoices/{invoice_id}/send:
        post:
            summary: Send invoice
            description: Sends or schedules an invoice, by ID, to be sent to a customer. The action depends on the invoice issue date:<ul><li>If the invoice issue date is current or in the past, sends the invoice immediately.</li><li>If the invoice issue date is in the future, schedules the invoice to be sent on that date.</li></ul>To suppress the merchant's email notification, set the `send_to_invoicer` body parameter to `false`. To send the invoice through a share link and not through PayPal, [...]
            operationId: invoices.send
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing/invoices/readwrite
            tags:
                - invoices
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v2/invoicing/invoices/{invoice_id}/remind:
        post:
            summary: Send invoice reminder
            description: Sends a reminder to the payer about an invoice, by ID. In the JSON request body, include a `notification` object that defines the subject of the reminder and other details.
            operationId: invoices.remind
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing/invoices/readwrite
            tags:
                - invoices
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v2/invoicing/invoices/{invoice_id}/cancel:
        post:
            summary: Cancel sent invoice
            description: 'Cancels a sent invoice, by ID, and, optionally, sends a notification about the cancellation to the payer, merchant, and CC: emails.'
            operationId: invoices.cancel
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing/invoices/readwrite
            tags:
                - invoices
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v2/invoicing/invoices/{invoice_id}/payments:
        post:
            summary: Record payment for invoice
            description: Records a payment for the invoice. If no payment is due, the invoice is marked as `PAID`. Otherwise, the invoice is marked as `PARTIALLY PAID`.
            operationId: invoices.payments
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing/invoices/readwrite
            tags:
                - invoices
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v2/invoicing/invoices/{invoice_id}/payments/{transaction_id}:
        delete:
            summary: Delete external payment
            description: Deletes an external payment, by invoice ID and transaction ID.
            operationId: invoices.payments-delete
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing/invoices/readwrite
            tags:
                - invoices
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v2/invoicing/invoices/{invoice_id}/refunds:
        post:
            summary: Record refund for invoice
            description: Records a refund for the invoice. If all payments are refunded, the invoice is marked as `REFUNDED`. Otherwise, the invoice is marked as `PARTIALLY REFUNDED`.
            operationId: invoices.refunds
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing/invoices/readwrite
            tags:
                - invoices
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v2/invoicing/invoices/{invoice_id}/refunds/{transaction_id}:
        delete:
            summary: Delete external refund
            description: Deletes an external refund, by invoice ID and transaction ID.
            operationId: invoices.refunds-delete
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing/invoices/readwrite
            tags:
                - invoices
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v2/invoicing/invoices/{invoice_id}/generate-qr-code:
        post:
            summary: Generate QR code
            description: Generates a QR code for an invoice, by ID. The QR code is a PNG image in <a href="https://www.base64encode.org/">Base64-encoded</a> format that corresponds to the invoice ID. You can generate a QR code for an invoice and add it to a paper or PDF invoice. When customers use their mobile devices to scan the QR code, they are redirected to the PayPal mobile payment flow where they can view the invoice and pay online with PayPal or a credit card. Before you get a QR code, yo[...]
            operationId: invoices.generate-qr-code
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing/invoices/readwrite
            tags:
                - invoices
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v2/invoicing/generate-next-invoice-number:
        post:
            summary: Generate invoice number
            description: Generates the next invoice number that is available to the merchant. The next invoice number uses the prefix and suffix from the last invoice number and increments the number by one. For example, the next invoice number after `INVOICE-1234` is `INVOICE-1235`.
            operationId: invoicing.generate-next-invoice-number
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing/invoices/readwrite
            tags:
                - invoices
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v2/invoicing/invoices/{invoice_id}:
        get:
            summary: Show invoice details
            description: Shows details for an invoice, by ID.
            operationId: invoices.get
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing/invoices/read
            tags:
                - invoices
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        put:
            summary: Fully update invoice
            description: Fully updates an invoice, by ID. In the JSON request body, include a complete `invoice` object. This call does not support partial updates.
            operationId: invoices.update
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing/invoices/readwrite
            tags:
                - invoices
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        delete:
            summary: Delete invoice
            description: Deletes a draft or scheduled invoice, by ID. Deletes invoices in the draft or scheduled state only. For invoices that have already been sent, you can <a href="/docs/api/invoicing/v2/#invoices_cancel">cancel the invoice</a>. After you delete a draft or scheduled invoice, you can no longer use it or show its details. However, you can reuse its invoice number.
            operationId: invoices.delete
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing/invoices/readwrite
            tags:
                - invoices
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v2/invoicing/search-invoices:
        post:
            summary: Search for invoices
            description: Searches for and lists invoices that match search criteria. If you pass multiple criteria, the response lists invoices that match all criteria.
            operationId: invoices.search-invoices
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing/invoices/read
            tags:
                - search-invoices
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v2/invoicing/templates:
        get:
            summary: List templates
            description: Lists merchant-created templates with associated details. The associated details include the emails, addresses, and phone numbers from the user's PayPal profile.<br/>The user can select which values to show in the business information section of their template.
            operationId: templates.list
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing/invoices/read
            tags:
                - templates
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        post:
            summary: Create template
            description: Creates an invoice template. You can use details from this template to create an invoice. You can create up to 50 templates.<blockquote><strong>Note:</strong> Every merchant starts with three PayPal system templates that are optimized for the unit type billed. The template includes `Quantity`, `Hours`, and `Amount`.</blockquote>
            operationId: templates.create
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing/invoices/readwrite
            tags:
                - templates
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v2/invoicing/templates/{template_id}:
        get:
            summary: Show template details
            description: Shows details for a template, by ID.
            operationId: templates.get
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing/invoices/read
            tags:
                - templates
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        put:
            summary: Fully update template
            description: Fully updates a template, by ID. In the JSON request body, include a complete `template` object. This call does not support partial updates.
            operationId: templates.update
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing/invoices/readwrite
            tags:
                - templates
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        delete:
            summary: Delete template
            description: Deletes a template, by ID.
            operationId: templates.delete
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/invoicing/invoices/readwrite
            tags:
                - templates
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/notifications/webhooks:
        post:
            summary: Create webhook
            description: Subscribes your webhook listener to events.
            operationId: webhooks.post
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/applications/webhooks
            tags:
                - webhooks
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        get:
            summary: List webhooks
            description: Lists webhooks for an app.
            operationId: webhooks.list
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/applications/webhooks
            tags:
                - webhooks
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/notifications/webhooks/{webhook_id}:
        get:
            summary: Show webhook details
            description: Shows details for a webhook, by ID.
            operationId: webhooks.get
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/applications/webhooks
            tags:
                - webhooks
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        patch:
            summary: Update webhook
            description: Updates a webhook to replace webhook fields with new values. Supports only the `replace` operation. Pass a `json_patch` object with `replace` operation and `path`, which is `/url` for a URL or `/event_types` for events. The `value` is either the URL or a list of events.
            operationId: webhooks.update
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/applications/webhooks
            tags:
                - webhooks
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        delete:
            summary: Delete webhook
            description: Deletes a webhook, by ID.
            operationId: webhooks.delete
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/applications/webhooks
            tags:
                - webhooks
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/notifications/webhooks/{webhook_id}/event-types:
        get:
            summary: List event subscriptions for webhook
            description: Lists event subscriptions for a webhook, by ID.
            operationId: event-types.list
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/applications/webhooks
            tags:
                - webhooks
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/notifications/webhooks-lookup:
        post:
            summary: Create webhook lookup
            description: Creates a webhook lookup.
            operationId: webhooks-lookup.post
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/applications/webhooks
            tags:
                - webhooks-lookup
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        get:
            summary: List webhook lookups
            description: Lists webhook lookups.
            operationId: webhooks-lookup.list
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/applications/webhooks
            tags:
                - webhooks-lookup
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/notifications/webhooks-lookup/{webhook_lookup_id}:
        get:
            summary: Show webhook lookup details
            description: Shows details for a webhook lookup, by ID.
            operationId: webhooks-lookup.get
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/applications/webhooks
            tags:
                - webhooks-lookup
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        delete:
            summary: Delete webhook lookup
            description: Deletes a webhook lookup, by ID.
            operationId: webhooks-lookup.delete
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/applications/webhooks
            tags:
                - webhooks-lookup
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/notifications/verify-webhook-signature:
        post:
            summary: Verify webhook signature
            description: Verifies a webhook signature.
            operationId: verify-webhook-signature.post
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/applications/webhooks
                    - https://uri.paypal.com/services/applications/verify-webhook-signature
            tags:
                - verify-webhook-signature
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/notifications/webhooks-event-types:
        get:
            summary: List available events
            description: Lists available events to which any webhook can subscribe. For a list of supported events, see [Webhook event names](/docs/api/notifications/webhooks/event-names/).
            operationId: webhooks-event-types.list
            tags:
                - webhooks-event-types
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/notifications/webhooks-events:
        get:
            summary: List event notifications
            description: Lists webhooks event notifications. Use query parameters to filter the response.
            operationId: webhooks-events.list
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/applications/webhooks
            tags:
                - webhooks-events
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/notifications/webhooks-events/{event_id}:
        get:
            summary: Show event notification details
            description: Shows details for a webhooks event notification, by ID.
            operationId: webhooks-events.get
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/applications/webhooks
            tags:
                - webhooks-events
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/notifications/webhooks-events/{event_id}/resend:
        post:
            summary: Resend event notification
            description: Resends a webhook event notification, by ID. Any pending notifications are not resent.
            operationId: webhooks-events.resend
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/applications/webhooks
            tags:
                - webhooks-events
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/notifications/simulate-event:
        post:
            summary: Simulate webhook event
            description: Simulates a webhook event. In the JSON request body, specify a sample payload.<br>You need to subscribe to the following webhook events for Pay upon Invoice:<br><table><thead><tr><th>Event</th><th>Trigger</th></tr></thead><tbody><tr><td><code>PAYMENT.CAPTURE.COMPLETED</code></td><td>A payment capture completes.</td></tr><tr><td><code>PAYMENT.CAPTURE.DENIED</code></td><td>A payment capture is denied.</td></tr><tr><td><code>CHECKOUT.PAYMENT-APPROVAL.REVERSED</code></td><td[...]
            operationId: simulate-event.post
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/applications/webhooks
            tags:
                - simulate-event
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/payment-experience/web-profiles:
        post:
            summary: Create web experience profile
            description: Creates a web experience profile. In the JSON request body, specify the profile name and details.
            operationId: web-profile.create
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                - Oauth2:
                    - https://uri.paypal.com/services/payments/realtimepayment
            tags:
                - web-profiles
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        get:
            summary: List web experience profiles
            description: Lists the latest 20 web experience profiles for a merchant or subject. To show details for these or additional profiles, you can show web experience profile details by ID.
            operationId: web-profile.get-list
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                - Oauth2:
                    - https://uri.paypal.com/services/payments/realtimepayment
            tags:
                - web-profiles
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/payment-experience/web-profiles/{id}:
        put:
            summary: Update web experience profile
            description: Updates a web experience profile, by ID. In the JSON request body, specify the profile details. If your request omits any profile parameters, any previously set values for those parameters are removed.
            operationId: web-profile.update
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                - Oauth2:
                    - https://uri.paypal.com/services/payments/realtimepayment
            tags:
                - web-profiles
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        patch:
            summary: Partially update web experience profile
            description: Partially-updates a web experience profile, by ID. In the JSON request body, specify a patch object, the path of the profile location to update, and a new value.
            operationId: web-profile.partial-update
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                - Oauth2:
                    - https://uri.paypal.com/services/payments/realtimepayment
            tags:
                - web-profiles
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        get:
            summary: Show web experience profile details by ID
            description: Shows details for a web experience profile, by ID.
            operationId: web-profile.get
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                - Oauth2:
                    - https://uri.paypal.com/services/payments/realtimepayment
            tags:
                - web-profiles
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        delete:
            summary: Delete web experience profile
            description: Deletes a web experience profile, by ID.
            operationId: web-profile.delete
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                - Oauth2:
                    - https://uri.paypal.com/services/payments/realtimepayment
            tags:
                - web-profiles
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/payments/payment:
        post:
            summary: Create payment
            description: '<blockquote><strong>Deprecation notice:</strong> The <code>/v1/payments</code> endpoint is deprecated. Use the <code>/v2/payments</code> endpoint instead. For details, see <a href="/docs/checkout/integrate/">PayPal Checkout Basic Integration</a>.</blockquote>Creates a sale, an authorized payment to be captured later, or an order. To create a sale, authorization, or order, include the payment details in the JSON request body. Set the <code>intent</code> to <code>sale</co[...]'
            operationId: payment.create
            security:
                - Oauth2:
                    - https://api.paypal.com/v1/payments/.*
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                - Oauth2:
                    - https://uri.paypal.com/services/payments/realtimepayment
                - Oauth2:
                    - https://uri.paypal.com/services/payments/paymentcard
                - Oauth2:
                    - https://uri.paypal.com/services/payments/channelpartner
            tags:
                - payment
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        get:
            summary: List payments
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/payments</code> endpoint is deprecated. Use the <code>/v2/payments</code> endpoint instead. For details, see <a href="/docs/checkout/integrate/">PayPal Checkout Basic Integration</a>.</blockquote>Lists payments that are completed. Payments that you just created with the <a href="/docs/api/payments/v1/#payment_create">create payment</a> call do not appear in the list.<br/><br/>The list shows the payments that [...]
            operationId: payment.list
            security:
                - Oauth2:
                    - https://api.paypal.com/v1/payments/.*
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                - Oauth2:
                    - https://uri.paypal.com/services/payments/realtimepayment
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment/authcapture
                - Oauth2:
                    - https://uri.paypal.com/services/checkout/onetimepayment
            tags:
                - payment
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/payments/payment/{payment_id}:
        get:
            summary: Show payment details
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/payments</code> endpoint is deprecated. Use the <code>/v2/payments</code> endpoint instead. For details, see <a href="/docs/checkout/integrate/">PayPal Checkout Basic Integration</a>.</blockquote>Shows details for a payment, by ID, that has yet to complete. For example, shows details for a payment that was created, approved, or failed.
            operationId: payment.get
            security:
                - Oauth2:
                    - https://api.paypal.com/v1/payments/.*
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                - Oauth2:
                    - https://uri.paypal.com/services/payments/realtimepayment
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment/authcapture
            tags:
                - payment
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
        patch:
            summary: Partially update payment
            description: '<blockquote><strong>Deprecation notice:</strong> The <code>/v1/payments</code> endpoint is deprecated. Use the <code>/v2/payments</code> endpoint instead. For details, see <a href="/docs/checkout/integrate/">PayPal Checkout Basic Integration</a>.</blockquote>Partially updates a payment, by ID. You can update the amount, shipping address, invoice ID, and custom data. You cannot update a payment after the payment executes. <blockquote><strong>Note: </strong>TPP Clients (T[...]'
            operationId: payment.update
            security:
                - Oauth2:
                    - https://api.paypal.com/v1/payments/.*
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                - Oauth2:
                    - https://uri.paypal.com/services/payments/realtimepayment
                - Oauth2:
                    - https://uri.paypal.com/services/payments/channelpartner
            tags:
                - payment
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/payments/payment/{payment_id}/execute:
        post:
            summary: Execute approved PayPal payment
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/payments</code> endpoint is deprecated. Use the <code>/v2/payments</code> endpoint instead. For details, see <a href="/docs/checkout/integrate/">PayPal Checkout Basic Integration</a>.</blockquote>Executes a PayPal payment that the customer has approved. You can optionally update one or more transactions when you execute the payment.<blockquote><strong>Important:</strong> This call works only after a customer [...]
            operationId: payment.execute
            security:
                - Oauth2:
                    - https://api.paypal.com/v1/payments/.*
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                - Oauth2:
                    - https://uri.paypal.com/services/payments/realtimepayment
            tags:
                - payment
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/payments/sale/{sale_id}:
        get:
            summary: Show sale details
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/payments</code> endpoint is deprecated. Use the <code>/v2/payments</code> endpoint instead. For details, see <a href="/docs/checkout/integrate/">PayPal Checkout Basic Integration</a>.</blockquote>Shows details for a sale, by ID. Returns only sales that were created through the REST API.
            operationId: sale.get
            security:
                - Oauth2:
                    - https://api.paypal.com/v1/payments/.*
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                - Oauth2:
                    - https://uri.paypal.com/services/payments/realtimepayment
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment/authcapture
            tags:
                - sale
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/payments/sale/{sale_id}/refund:
        post:
            summary: Refund sale
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/payments</code> endpoint is deprecated. Use the <code>/v2/payments</code> endpoint instead. For details, see <a href="/docs/checkout/integrate/">PayPal Checkout Basic Integration</a>.</blockquote>Refunds a sale, by ID. For a full refund, do not include the <code>amount</code> object in the JSON request body. For a partial refund, include an <code>amount</code> object in the JSON request body.
            operationId: sale.refund
            security:
                - Oauth2:
                    - https://api.paypal.com/v1/payments/.*
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                - Oauth2:
                    - https://uri.paypal.com/services/payments/refund
                - Oauth2:
                    - https://uri.paypal.com/services/payments/unilateralrefund
            tags:
                - sale
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/payments/authorization/{authorization_id}:
        get:
            summary: Show authorization details
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/payments</code> endpoint is deprecated. Use the <code>/v2/payments</code> endpoint instead. For details, see <a href="/docs/checkout/integrate/">PayPal Checkout Basic Integration</a>.</blockquote>Shows details for an authorization, by ID.
            operationId: authorization.get
            security:
                - Oauth2:
                    - https://api.paypal.com/v1/payments/.*
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                - Oauth2:
                    - https://uri.paypal.com/services/payments/realtimepayment
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment/authcapture
            tags:
                - authorization
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/payments/authorization/{authorization_id}/capture:
        post:
            summary: Capture authorization
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/payments</code> endpoint is deprecated. Use the <code>/v2/payments</code> endpoint instead. For details, see <a href="/docs/checkout/integrate/">PayPal Checkout Basic Integration</a>.</blockquote>Captures and processes an authorization, by ID. The original payment call must specify an intent of <code>authorize</code>.
            operationId: authorization.capture
            security:
                - Oauth2:
                    - https://api.paypal.com/v1/payments/.*
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment/authcapture
            tags:
                - authorization
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/payments/authorization/{authorization_id}/void:
        post:
            summary: Void authorization
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/payments</code> endpoint is deprecated. Use the <code>/v2/payments</code> endpoint instead. For details, see <a href="/docs/checkout/integrate/">PayPal Checkout Basic Integration</a>.</blockquote>Voids, or cancels, an authorization, by ID. You cannot void a fully captured authorization.
            operationId: authorization.void
            security:
                - Oauth2:
                    - https://api.paypal.com/v1/payments/.*
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment/authcapture
            tags:
                - authorization
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/payments/authorization/{authorization_id}/reauthorize:
        post:
            summary: Re-authorize payment
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/payments</code> endpoint is deprecated. Use the <code>/v2/payments</code> endpoint instead. For details, see <a href="/docs/checkout/integrate/">PayPal Checkout Basic Integration</a>.</blockquote>Re-authorizes a PayPal account payment, by authorization ID. To ensure that funds are still available, re-authorize a payment after the initial three-day honor period. Supports only the <code>amount</code> request pa[...]
            operationId: authorization.reauthorize
            security:
                - Oauth2:
                    - https://api.paypal.com/v1/payments/.*
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment/authcapture
            tags:
                - authorization
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/payments/orders/{order_id}:
        get:
            summary: Show order details
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/payments</code> endpoint is deprecated. Use the <code>/v2/payments</code> endpoint instead. For details, see <a href="/docs/checkout/integrate/">PayPal Checkout Basic Integration</a>.</blockquote>Shows details for an order, by ID.
            operationId: orders.get
            security:
                - Oauth2:
                    - https://api.paypal.com/v1/payments/.*
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                - Oauth2:
                    - https://uri.paypal.com/services/payments/realtimepayment
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment/authcapture
            tags:
                - orders
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/payments/orders/{order_id}/capture:
        post:
            summary: Capture order
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/payments</code> endpoint is deprecated. Use the <code>/v2/payments</code> endpoint instead. For details, see <a href="/docs/checkout/integrate/">PayPal Checkout Basic Integration</a>.</blockquote>Captures a payment for an order, by ID. To use this call, the original payment call must specify an <code>order</code> intent. In the JSON request body, include the payment amount and indicate whether this capture is[...]
            operationId: orders.capture
            security:
                - Oauth2:
                    - https://api.paypal.com/v1/payments/.*
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment/authcapture
            tags:
                - orders
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/payments/orders/{order_id}/do-void:
        post:
            summary: Void order
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/payments</code> endpoint is deprecated. Use the <code>/v2/payments</code> endpoint instead. For details, see <a href="/docs/checkout/integrate/">PayPal Checkout Basic Integration</a>.</blockquote>Voids, or cancels, an order, by ID. You can only void orders that are either in the <code>PENDING</code> or <code>AUTHORIZED</code> states or those in the <code>CAPTURED</code> state that are not fully captured.
            operationId: orders.void
            security:
                - Oauth2:
                    - https://api.paypal.com/v1/payments/.*
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment/authcapture
            tags:
                - orders
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/payments/orders/{order_id}/authorize:
        post:
            summary: Authorize order
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/payments</code> endpoint is deprecated. Use the <code>/v2/payments</code> endpoint instead. For details, see <a href="/docs/checkout/integrate/">PayPal Checkout Basic Integration</a>.</blockquote>Authorizes an order, by ID. In the JSON request body, include an <code>amount</code> object.
            operationId: orders.authorize
            security:
                - Oauth2:
                    - https://api.paypal.com/v1/payments/.*
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment/authcapture
            tags:
                - orders
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/payments/capture/{capture_id}:
        get:
            summary: Show captured payment details
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/payments</code> endpoint is deprecated. Use the <code>/v2/payments</code> endpoint instead. For details, see <a href="/docs/checkout/integrate/">PayPal Checkout Basic Integration</a>.</blockquote>Shows details for a captured payment, by ID.
            operationId: capture.get
            security:
                - Oauth2:
                    - https://api.paypal.com/v1/payments/.*
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                - Oauth2:
                    - https://uri.paypal.com/services/payments/realtimepayment
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment/authcapture
            tags:
                - capture
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/payments/capture/{capture_id}/refund:
        post:
            summary: Refund captured payment
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/payments</code> endpoint is deprecated. Use the <code>/v2/payments</code> endpoint instead. For details, see <a href="/docs/checkout/integrate/">PayPal Checkout Basic Integration</a>.</blockquote>Refunds a captured payment, by ID. In the JSON request body, include an <code>amount</code> object.
            operationId: capture.refund
            security:
                - Oauth2:
                    - https://api.paypal.com/v1/payments/.*
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                - Oauth2:
                    - https://uri.paypal.com/services/payments/refund
                - Oauth2:
                    - https://uri.paypal.com/services/payments/unilateralrefund
            tags:
                - capture
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/payments/refund/{refund_id}:
        get:
            summary: Show refund details
            description: <blockquote><strong>Deprecation notice:</strong> The <code>/v1/payments</code> endpoint is deprecated. Use the <code>/v2/payments</code> endpoint instead. For details, see <a href="/docs/checkout/integrate/">PayPal Checkout Basic Integration</a>.</blockquote>Shows details for a refund, by ID.
            operationId: refund.get
            security:
                - Oauth2:
                    - https://api.paypal.com/v1/payments/.*
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment
                - Oauth2:
                    - https://uri.paypal.com/services/payments/refund
            tags:
                - refund
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v2/payments/authorizations/{authorization_id}:
        get:
            summary: Show details for authorized payment
            description: Shows details for an authorized payment, by ID.
            operationId: authorizations.get
            tags:
                - authorizations
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment/authcapture
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v2/payments/authorizations/{authorization_id}/capture:
        post:
            summary: Capture authorized payment
            description: Captures an authorized payment, by ID.
            operationId: authorizations.capture
            tags:
                - authorizations
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment/authcapture
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v2/payments/authorizations/{authorization_id}/reauthorize:
        post:
            summary: Reauthorize authorized payment
            description: Reauthorizes an authorized PayPal account payment, by ID. To ensure that funds are still available, reauthorize a payment after its initial three-day honor period expires. Within the 29-day authorization period, you can issue multiple re-authorizations after the honor period expires.<br/><br/>If 30 days have transpired since the date of the original authorization, you must create an authorized payment instead of reauthorizing the original authorized payment.<br/><br/>A r[...]
            operationId: authorizations.reauthorize
            tags:
                - authorizations
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment/authcapture
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v2/payments/authorizations/{authorization_id}/void:
        post:
            summary: Void authorized payment
            description: Voids, or cancels, an authorized payment, by ID. You cannot void an authorized payment that has been fully captured.
            operationId: authorizations.void
            tags:
                - authorizations
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment/authcapture
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v2/payments/captures/{capture_id}:
        get:
            summary: Show captured payment details
            description: Shows details for a captured payment, by ID.
            operationId: captures.get
            tags:
                - captures
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/payments/payment/authcapture
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v2/payments/captures/{capture_id}/refund:
        post:
            summary: Refund captured payment
            description: Refunds a captured payment, by ID. For a full refund, include an empty payload in the JSON request body. For a partial refund, include an <code>amount</code> object in the JSON request body.
            operationId: captures.refund
            tags:
                - captures
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/payments/refund
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v2/payments/refunds/{refund_id}:
        get:
            summary: Show refund details
            description: Shows details for a refund, by ID.
            operationId: refunds.get
            tags:
                - refunds
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/payments/refund
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/payments/payouts:
        post:
            summary: Create batch payout
            description: Creates a batch payout. In the JSON request body, pass a `sender_batch_header` and an `items` array. The `sender_batch_header` defines how to handle the payout. The `items` array defines the payout items.<br/>You can make payouts to one or more recipients.<blockquote><strong>Notes:</strong> <ul><li><p>PayPal does not process duplicate payouts. If you specify a <code>sender_batch_id</code> that was used in the last 30 days, the API rejects the request with an error messag[...]
            operationId: payouts.post
            security:
                - Oauth2:
                    - https://uri.paypal.com/payments/payouts
            tags:
                - payouts
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/payments/payouts/{id}:
        get:
            summary: Show payout batch details
            description: Shows the latest status of a batch payout. Includes the transaction status and other data for individual payout items.
            operationId: payouts.get
            security:
                - Oauth2:
                    - https://uri.paypal.com/payments/payouts
            tags:
                - payouts
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/payments/payouts-item/{payout_item_id}:
        get:
            summary: Show payout item details
            description: Shows details for a payout item, by ID. A <code>payout_item_id</code> helps you identify denied payments. If a payment is denied, you can use the <code>payout_item_id</code> to identify the payment even if it lacks a <code>transaction_id</code>.
            operationId: payouts-item.get
            security:
                - Oauth2:
                    - https://uri.paypal.com/payments/payouts
            tags:
                - payouts-item
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/payments/payouts-item/{payout_item_id}/cancel:
        post:
            summary: Cancel unclaimed payout item
            description: Cancels an unclaimed payout item, by ID. If no one claims the unclaimed item within 30 days, the API automatically returns the funds to the sender. Use this call to cancel the unclaimed item before the automatic 30-day refund. You can cancel payout items with a <code>transaction_status</code> of <code>UNCLAIMED</code>.
            operationId: payouts-item.cancel
            security:
                - Oauth2:
                    - https://uri.paypal.com/payments/payouts
            tags:
                - payouts-item
            servers:
                - url: https://api-m.sandbox.paypal.com
                  description: PayPal Sandbox Environment
                - url: https://api-m.paypal.com
                  description: PayPal Live Environment
    /v1/reporting/transactions:
        get:
            summary: List transactions
            description: Lists transactions. Specify one or more query parameters to filter the transaction that appear in the response.<blockquote><strong>Notes:</strong> <ul><li>If you specify one or more optional query parameters, the <code>ending_balance</code> response field is empty.</li><li>It takes a maximum of three hours for executed transactions to appear in the list transactions call.</li><li>This call lists transaction for the previous three years.</li></ul></blockquote>
            operationId: search.get
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/reporting/search/read
            tags:
                - transactions
            servers:
                - url: https://api-m.paypal.com/v1/reporting
    /v1/reporting/balances:
        get:
            summary: List all balances
            description: List all balances. Specify date time to list balances for that time that appear in the response.<blockquote><strong>Notes:</strong> <ul><li>It takes a maximum of three hours for balances to appear in the list balances call.</li><li>This call lists balances upto the previous three years.</li></ul></blockquote>
            operationId: balances.get
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/reporting/balances/read
            tags:
                - balances
            servers:
                - url: https://api-m.paypal.com/v1/reporting
    /v1/shipping/trackers-batch:
        post:
            summary: Add tracking information for multiple PayPal transactions
            description: Adds tracking information, with or without tracking numbers, for multiple PayPal transactions. Accepts up to 20 tracking IDs. For more information, see <a href="/docs/tracking/integrate/#add-tracking-information-with-tracking-numbers">Add tracking information with tracking numbers</a> and <a href="/docs/tracking/integrate/#add-tracking-information-without-tracking-numbers">Add tracking information without tracking numbers</a>.
            operationId: trackers-batch.post
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/shipping/trackers/readwrite
            tags:
                - trackers-batch
    /v1/shipping/trackers:
        post:
            summary: Add tracking information for PayPal transaction
            description: Adds tracking information for a PayPal transaction.
            operationId: trackers.post
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/shipping/trackers/readwrite
            tags:
                - trackers
        get:
            summary: List tracking information
            description: Lists tracking information that meet search criteria. The tracking ID is required but the tracking number is optional.
            operationId: trackers-batch.get
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/shipping/trackers/read
            tags:
                - trackers
    /v1/shipping/trackers/{id}:
        put:
            summary: Update or cancel tracking information for PayPal transaction
            description: Updates or cancels the tracking information for a PayPal transaction, by ID. To cancel tracking information, call this method and set the status to CANCELLED. For more information, see <a href="/docs/tracking/integrate/#update-or-cancel-tracking-information">Update or cancel tracking information</a>.
            operationId: trackers.put
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/shipping/trackers/readwrite
            tags:
                - trackers
        get:
            summary: Show tracking information
            description: Shows tracking information, by tracker ID, for a PayPal transaction.
            operationId: trackers.get
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/shipping/trackers/read
            tags:
                - trackers
    /v3/vault/payment-tokens:
        post:
            description: Creates a Payment Token from the given payment source and adds it to the Vault of the associated customer.
            summary: Create payment token for a given payment source
            operationId: payment-tokens.create
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/vault/payment-tokens/readwrite
            tags:
                - payment-tokens
        get:
            description: Returns all payment tokens for a customer.
            summary: List all payment tokens
            operationId: customer.payment-tokens.get
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/vault/payment-tokens/readwrite
            tags:
                - payment-tokens
    /v3/vault/payment-tokens/{id}:
        get:
            description: Returns a readable representation of vaulted payment source associated with the payment token id.
            summary: Retrieve a payment token
            operationId: payment-tokens.get
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/vault/payment-tokens/readwrite
            tags:
                - payment-tokens
        delete:
            description: Delete the payment token associated with the payment token id.
            summary: Delete payment token
            operationId: payment-tokens.delete
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/vault/payment-tokens/readwrite
            tags:
                - payment-tokens
    /v3/vault/setup-tokens:
        post:
            description: Creates a Setup Token from the given payment source and adds it to the Vault of the associated customer.
            summary: Create a setup token
            operationId: setup-tokens.create
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/vault/payment-tokens/read
            tags:
                - setup-tokens
    /v3/vault/setup-tokens/{id}:
        get:
            description: Returns a readable representation of temporarily vaulted payment source associated with the setup token id.
            summary: Retrieve a setup token
            operationId: setup-tokens.get
            security:
                - Oauth2:
                    - https://uri.paypal.com/services/vault/payment-tokens/read
            tags:
                - setup-tokens
components:
    securitySchemes:
        Oauth2:
            type: oauth2
            description: Oauth 2.0 authentication
            flows:
                clientCredentials:
                    tokenUrl: /v1/oauth2/token
                    scopes:
                        https://uri.paypal.com/services/vault/payment-tokens/readwrite: Manage payment instruments
                        https://uri.paypal.com/services/vault/payment-tokens/read: Permission to only read from vault
                        https://uri.paypal.com/services/vault/customers/read: Permission to read customer information.
                        https://uri.paypal.com/services/vault/customers/readwrite: Permission to create/update customer information.